### ISSUE TITLE
hange the settings to printer settings and reduce options

### ISSUE THREAD

**Issue by aditya6992** [aditya6992/youWouldntKnowWhatThisShitIs#3]

**Comment by alanturin** [comment]
contact me on skype: pocak.tocsa

I am from getacoder

**Comment by spondox** [comment]
What?

**Comment by aditya6992** [comment]
i do not have skype access in my university

On Fri, May 22, 2015 at 10:50 AM, spondox <notifications@github.com> wrote:

> What?
>
> On May 21, 2015 1:20 PM, "alanturin" <notifications@github.com> wrote:
>
> > contact me on skype: pocak.tocsa
> >
> > I am from getacoder
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/aditya6992/youWouldntKnowWhatThisShitIs/issues/3#issuecomment-104169324
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aditya6992/youWouldntKnowWhatThisShitIs/issues/3#issuecomment-104513204>
> .
>



-- 
*ADITYA SISTA*

**Comment by alanturin** [comment]
wrote you on gmail
